apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.threefoldVdc.backup }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  {{- end }}
  name: tftbscbridge-volume-claim-{{ .Release.Name }}
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}