//Package tokencontract contains the go bindings for the TFT contract
//The binding is generated by executing `go generate .`in this folder
package tokencontract

//go:generate abigen --abi ../../abis/TFT.abi --pkg tokencontract --type Token --out token.go
