//Package contract contains the go bindings for the TFT contract
//The bindings are generated by executing `go generate .`in this folder
package contract

//go:generate abigen --abi ../../abis/TFT.abi --pkg contract --type Token --out token.go
