//Package contract contains the go bindings for the smart contracts
//The bindings are generated by executing `go generate .`in this folder
package contract

//go:generate abigen --abi ../../abis/mscontract.abi --pkg contract --type MultiSig --out multisig.go
//go:generate abigen --abi ../../abis/TFT.abi --pkg contract --type Token --out token.go
