//Package mscontracts contains the go bindings for the Multisig contract
//The binding is generated by executing `go generate .`in this folder
package mscontract

//go:generate abigen --abi ../../abis/mscontract.abi --pkg mscontract --type MultiSig --out multisig.go
