name: Publish Helm charts

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
            tag: ${{ github.ref }}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
              GITHUB_TOKEN: ${{ github.token }}

      - name: Package tftbscbridge chart
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm package -d packagedcharts --app-version ${{ steps.semver.outputs.non-prefixed }} --version ${{ steps.semver.outputs.non-prefixed }} bsc/helmchart/tftbscbridge

      - name: Upload tftbscbridge packaged chart
        uses: actions/upload-release-asset@v1.0.2
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.get_release.outputs.upload_url }}
              asset_path: packagedcharts/tftbscbridge-${{ steps.semver.outputs.non-prefixed }}.tgz
              asset_name: tftbscbridge-${{ steps.semver.outputs.non-prefixed }}.tgz
              asset_content_type: application/gzip


      - name: Package tftethbridge chart
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm package -d packagedcharts --app-version ${{ steps.semver.outputs.non-prefixed }} --version ${{ steps.semver.outputs.non-prefixed }} ethereum/helmchart/tftethbridge

      - name: Upload tftethbridge packaged chart
        uses: actions/upload-release-asset@v1.0.2
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: packagedcharts/tftethbridge-${{ steps.semver.outputs.non-prefixed }}.tgz
            asset_name: tftethbridge-${{ steps.semver.outputs.non-prefixed }}.tgz
            asset_content_type: application/gzip

      